In [3]:
import json
import pandas as pd

In [9]:
# Load JSON data from a file
file_path = 'all.json'  # Replace with your file path

with open(file_path, 'r') as file:
    json_data = json.load(file)

# Extract security company name and sector
securities = json_data['data']['watch']
extracted_data = []

for security in securities:
    company_name = security['companyname']
    sector = security['sector']
    ticker = security['security']
    extracted_data.append({'company_name': company_name, 'security': ticker, 'sector': sector})

# Create a pandas DataFrame
df = pd.DataFrame(extracted_data)

In [10]:
df

                             company_name    security sector
0                      MAHARAJA FOODS PLC  MFPE.N0000   3020
1    DIGITAL MOBILITY SOLUTIONS LANKA PLC  PKME.N0000   2030
2                     CABLE SOLUTIONS PLC  CSLK.N0000   2010
3                       CARGILLS BANK PLC  CBNK.N0000   4010
4                          UB FINANCE PLC   UBF.N0000   4020
..                                    ...         ...    ...
586         EXTERMINATORS PLC (EXT.B0000)   EXT.B0000   3030
587   COLOMBO INVESTMENT TRUST PLC(BONUS)   CIT.B0000   null
588        CENTRAL INDUSTRIES PLC (Bonus)  CIND.B0000   null
589          COLOMBO FORT INVESTMENTS PLC   CFI.B0000   null
590            AMANA BANK PLC (ABL.B0000)   ABL.B0000   null

[591 rows x 3 columns]

In [11]:
df.to_csv("stock_info.csv")